version: '3.9'
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chroniclex
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    restart: unless-stopped
  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/chroniclex
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET:-changemepleasechangeme}
      GRAPHQL_PLAYGROUND: 'false'
      NODE_ENV: production
    depends_on:
      - db
      - redis
    ports:
      - '4000:4000'
  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000
      NODE_ENV: production
    depends_on:
      - backend
    ports:
      - '3000:3000'
volumes:
  db_data: {}
