# Railway Nixpacks config (pnpm monorepo + Prisma + Fastify)
# Forces Node provider and uses workspace-aware installs.

providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = [
  "corepack enable",
  "corepack prepare pnpm@9.6.0 --activate",
  "pnpm -w install --frozen-lockfile --filter @chroniclex/backend...",
  "pnpm prisma:generate"
]

[phases.build]
cmds = [
  "pnpm build"
]

[start]
cmd = "pnpm start"
