# Railway/Nixpacks configuration for pnpm + Prisma + Fastify backend
[variables]
NODE_VERSION = "20"

[install]
# Use pnpm; install at workspace root, then generate Prisma client in backend
cmds = [
  "set -e",
  "corepack enable",
  "corepack prepare pnpm@9.6.0 --activate",
  "cd ../.. && pnpm install --frozen-lockfile && cd packages/backend",
  "pnpm prisma:generate"
]

[build]
cmds = [
  "pnpm build"
]

[start]
cmd = "pnpm start"
